openapi: "3.0.2"
info:
  description: "This is the API documentation for the management and budget services of \
  SPQ Express.  More information can be found in the links below."
  version: "0.0.1"
  title: "SPQ Express"
  termsOfService: "https://www.spqexpress.com/tos"
  contact:
    email: "jcatronspqx@gmail.com"
  license:
    name: "Private License"
    url: "https://www.spqexpress/license"
externalDocs:
  description: "Find out more about SPQ Express"
  url: "https://www.spqexpress.com"
tags:
- name: "Management"
  description: "Management of products used for price calculation"
  externalDocs:
    description: "For more information"
    url: "https://www.spqexpress.com/services/management"
- name: "Pricing"
  description: "Price calculation service"
  externalDocs:
    description: "For more information"
    url: "https://www.spqexpress.com/services/pricing"
paths:
  /products:
    get:
      summary: List product configurations
      description: >
        This resource provides a list of products in the system.
        Each product will be unique by numeric `id`.
      responses:

      tags:
        - "Management"
    post:
      summary: Create a product configuration
      description: >
        This resource creates a new product configuration in the system.
        The product will be saved with the provided configuration and a
        unique `id` generated by the system.
      responses:

      tags:
        - "Management"
